name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        components: clippy, rustfmt
    - name: Format
      run: cargo fmt --check
    - name: Clippy
      run: cargo clippy -- -D warnings
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [1.54.0, stable, beta, nightly]
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ matrix.toolchain }}
        components: clippy, rustfmt
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
  msrv:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
    - name: Install `cargo-msrv`
      run: cargo install cargo-msrv
    - name: Verify MSRV
      run: cargo msrv verify
